### each of the main pages
# Analysis
pages_analysis <- tabPanel("Analysis", 
								sidebarLayout(
									shinyUI_Panel_inupt, 
									shinyUI_Panel_main
								) # Sidebar layout
                           )
# About
pages_about <- tabPanel("About",
		fluidRow(
			column(width = 4, wellPanel(
			HTML("Created by A. Kennedy, E. Richardson, J. Higham, P. Kotsantis, R. Mort, B. Shih. <br/> <br/> 
					This tool was created with funding from North West Cancer Research. The analysis used in Evergene are based on data generated by the "),
			tags$a( "TCGA Research network", target = "_blank", href = " https://www.cancer.gov/tcga"	),
			HTML(". Stemness index (sample annotation) came from "),
			tags$a( "Malta et al. (2018)", target = "_blank", href = "doi:10.1016/j.cell.2018.03.034"	),
			HTML(". Immune subtype (sample annotation) came from "),
			tags$a( "Thorsson et al. (2018)", target = "_blank", href = "doi:10.1016/j.immuni.2018.03.023"	),
			HTML("Clinical events and other sample annotation came from "),
			tags$a( "Liu et al. (2018)", target = "_blank", href = "doi:10.1016/j.cell.2018.02.052"	),
			HTML(".<br><br>In addition to the acknowledgements above, we would like to thank all participating patients and clinicians for contributing to the TCGA project."),
		), # Well panel
		  img(src='nwcr.png', height="50%", width="60%"), 
		  img(src='lu.png', height="50%", width="60%")
		  ), # Column
		  
		  column(width = 8, wellPanel(
		    HTML("This webtool allows users to perform principal component analysis (PCA), survival analysis (SA) and correlation analysis (CA) using TCGA (The Cancer Genome Atlas) data. Additionally, users can upload their own data for PCA and CA. 
				The source code for this Evergene is available in " ),
			tags$a( "GitHub", target = "_blank", href = "https://github.com/bshihlab/evergene"	),
		    HTML(". <br><br>Evergene focuses on multiple-input single-gene analysis and outputs, with an emphasis on visualisation of sample annotation. We recommand the following tools for other related analysis types not covered by Evergene." ),
		    HTML("<br>Survival analysis with a gene set: "),
			tags$a( "Survival Genie", target = "_blank", href = "https://bhasinlab.bmi.emory.edu/SurvivalGenie/"	),
		    HTML(", "),
			tags$a( "GEPIA2", target = "_blank", href = "http://gepia2.cancer-pku.cn/#index"	),
		    HTML("<br>Survival analysis with custom data: "),
			tags$a( "KM plotter", target = "_blank", href = "https://kmplot.com/analysis/"	),
			
			#  HTML('<iframe width="560" height="315" src="https://www.youtube.com/embed/Ka2pWqXS1WA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>')
		  ) # Well panel
		  ) # Column
		)  # Fluid row
	) # Tab panel

# Contact us
pages_contactUs <- tabPanel("Contact us")

# Source page
pages_source <- tabPanel("Source code", 
	HTML('<script src="https://emgithub.com/embed-v2.js?target=https%3A%2F%2Fgithub.com%2Fellaintheclouds%2FNWCR%2Fblob%2Fmain%2FPCA_function.R&style=default&type=code&showBorder=on&showLineNumbers=on&showFileMeta=on&showFullPath=on&showCopy=on"></script>'))
	
# Documentation

#pages_documentation <- tabPanel("Home", href = "https://google.com", style = "color:white;")
pages_documentation <- tabPanel("Documentation", tags$iframe(style="height:800px; width:100%; scrolling=yes", src="documentation.pdf"))
	